export const APP_VERSION = '1.3.0';

export const STATS = {
  sleepiness: { label: 'Сонливость', type: 'negative', loseAt: 100 },
  suspicion: { label: 'Подозрение учителя', type: 'negative', loseAt: 100 },
  stress: { label: 'Стресс', type: 'negative', loseAt: 100 },
  knowledge: { label: 'Знания', type: 'positive', loseAt: null },
  score: { label: 'Очки', type: 'score', loseAt: null },
};

export const MODES = {
  normal: {
    id: 'normal',
    title: 'Обычный урок',
    objective: 'Дожить до звонка.',
    resultWinTitle: 'Звонок! Обычный урок пережит 🎉',
    resultWinText: 'Ты дожил до конца урока и не спалился.',
    timeLabel: 'До звонка',
    durationSec: 180,
    tickMs: 1000,
    baseDrift: { sleepiness: 1.05, stress: 0.75, suspicion: 0.18, knowledge: 0.12 },
    eventEverySec: [8, 12],
    difficultyScale: 1,
    endlessRampPerMinute: 0,
    scorePerSecond: 0.7,
    knowledgeScoreFactor: 70,
    survivalBonus: 100,
    knowledgeEffectiveness: 1,
    suspicionPenaltyScale: 1,
    stressPenaltyScale: 1,
    importantFailEndsRun: true,
    eventWeights: {},
    unlockScore: 0,
  },
  test: {
    id: 'test',
    title: 'Контрольная',
    objective: 'Выжить до конца контрольной.',
    resultWinTitle: 'Контрольная пережита ✅',
    resultWinText: 'Ты выдержал давление до самого конца.',
    timeLabel: 'До конца контрольной',
    durationSec: 150,
    tickMs: 1000,
    baseDrift: { sleepiness: 0.95, stress: 1.45, suspicion: 0.38, knowledge: 0.07 },
    eventEverySec: [5, 8],
    difficultyScale: 1.3,
    endlessRampPerMinute: 0,
    scorePerSecond: 0.85,
    knowledgeScoreFactor: 55,
    survivalBonus: 170,
    knowledgeEffectiveness: 1.35,
    suspicionPenaltyScale: 1.25,
    stressPenaltyScale: 1.2,
    importantFailEndsRun: true,
    eventWeights: {
      mini_test: 2.1,
      called_to_answer: 1.8,
      board_call: 1.35,
      phone_message: 0.6,
    },
    unlockScore: 220,
  },
  endless: {
    id: 'endless',
    title: 'Бесконечный режим',
    objective: 'Держись как можно дольше и бей рекорд.',
    resultWinTitle: 'Рекордный забег завершён 🏁',
    resultWinText: 'Звонка нет — здесь важны только выживание и очки.',
    timeLabel: 'Выжито',
    durationSec: null,
    tickMs: 1000,
    baseDrift: { sleepiness: 1.2, stress: 1.15, suspicion: 0.3, knowledge: 0.09 },
    eventEverySec: [5, 8],
    difficultyScale: 1.2,
    endlessRampPerMinute: 0.12,
    scorePerSecond: 1,
    knowledgeScoreFactor: 65,
    survivalBonus: 0,
    knowledgeEffectiveness: 1,
    suspicionPenaltyScale: 1.05,
    stressPenaltyScale: 1.05,
    importantFailEndsRun: true,
    eventWeights: {
      sleep_attack: 1.35,
      teacher_look: 1.2,
      phone_message: 1.2,
    },
    unlockScore: 420,
  },
};

export const ACTIONS = [
  { id: 'listen', label: 'Слушать' },
  { id: 'pretend', label: 'Делать вид, что работаешь' },
  { id: 'phone', label: 'Сидеть в телефоне' },
  { id: 'cheat', label: 'Списывать' },
  { id: 'answer', label: 'Отвечать' },
  { id: 'ignore', label: 'Игнорировать' },
  { id: 'excuse', label: 'Отмазаться' },
  { id: 'leave', label: 'Попроситься выйти' },
];

export const LOSS_REASON = {
  suspicion: 'Учитель раскусил тебя. Конец маскировки.',
  sleepiness: 'Ты уснул прямо на уроке. Поражение.',
  stress: 'Нервы не выдержали, и ты сдался.',
  eventFail: 'Ты провалил ключевое событие.',
};

export const RUN_END_TYPE = {
  LOSE: 'lose',
  TIME_WIN: 'time_win',
  ENDLESS_RECORD: 'endless_record',
};
