const D = {
  low: 'низкая',
  medium: 'средняя',
  high: 'высокая',
};

export const EVENTS = [
  {
    id: 'teacher_look',
    title: 'Учитель смотрит в твою сторону.',
    danger: D.medium,
    weight: 1.3,
    minProgress: 0,
    cooldown: 2,
    checks: ['pretend', 'listen', 'phone'],
  },
  {
    id: 'called_to_answer',
    title: 'Тебя спрашивают по теме!',
    danger: D.high,
    weight: 1.1,
    minProgress: 0.08,
    cooldown: 2,
    checks: ['answer', 'excuse', 'ignore'],
    important: true,
  },
  {
    id: 'neighbor_help',
    title: 'Сосед просит помочь с задачей.',
    danger: D.low,
    weight: 1,
    minProgress: 0.1,
    cooldown: 1,
    checks: ['answer', 'ignore', 'cheat'],
  },
  {
    id: 'phone_message',
    title: 'Пришло сообщение на телефон.',
    danger: D.medium,
    weight: 1.2,
    minProgress: 0,
    cooldown: 2,
    checks: ['phone', 'ignore', 'pretend'],
  },
  {
    id: 'sleep_attack',
    title: 'Глаза закрываются... хочется спать.',
    danger: D.medium,
    weight: 1.2,
    minProgress: 0,
    cooldown: 1,
    checks: ['listen', 'leave', 'ignore'],
  },
  {
    id: 'notebook_check',
    title: 'Проверка тетрадей начинается.',
    danger: D.medium,
    weight: 1.1,
    minProgress: 0.2,
    cooldown: 2,
    checks: ['pretend', 'cheat', 'excuse'],
  },
  {
    id: 'mini_test',
    title: 'Мини-контрольная на 5 минут!',
    danger: D.high,
    weight: 1,
    minProgress: 0.35,
    cooldown: 3,
    checks: ['answer', 'cheat', 'excuse'],
    important: true,
  },
  {
    id: 'board_call',
    title: 'Вызов к доске! Все смотрят на тебя.',
    danger: D.high,
    weight: 1,
    minProgress: 0.5,
    cooldown: 3,
    checks: ['answer', 'excuse', 'leave'],
    important: true,
  },
];
